//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : Andrias_Davidianus.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public class Andrias_Davidianus : Species
{
}
