//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : AreaEnum.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public enum AreaEnum 
{
	松潘县,
	南坪县,
	平武县,
	青川县,
	茂县,
	北川县
}
