//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : Big_Panda.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public class Big_Panda : Big_Panda, Species
{
}
