//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : Picea_Brachytyla.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public class Picea_Brachytyla : Plant
{
}
