//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : PlantTypeEnum.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public enum PlantTypeEnum
{
    灌木林,
    高覆盖草地,
    针叶林,
    中覆盖草地,
    混交林,
    低覆盖草地,
    阔叶林,
    农业用地
}
