//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : Plant.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public class Plant 
{
	private int suitHeight = 0;
	private AreaEnum suitArea ;
	private PlantTypeEnum suitPlantType ;
}
