//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : Species.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//


public class Species 
{
	public int bestHeight = 0;
	public int generalHeight = 0;
	public int unsuitableHeight = 0;
	public PlanTypeEnum bestPlantType = 0;
	public PlanTypeEnum generalPlantType = 0;
	private PlanTypeEnum unsuitablePlantType = 0;
}
