//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : 岷山景观保护系统
//  @ File Name : Species.cs
//  @ Date : 2014/4/16 星期三
//  @ Author : Jacory Gao
//
//



public class Species 
{
	public int bestHeight = 0;
	public int generalHeight = 0;
	public int unsuitableHeight = 0;
	public int bestPlantType = 0;
	public int generalPlantType = 0;
	private int unsuitablePlantType = 0;
}
